### PR TITLE
update to 3.1.0.16661

### PR DESCRIPTION
**Pull request by thehomerepot**

### CODE REVIEW

**Comment by paxsecurity** [comment]
Hello, I was wondering how are you implementing this container? What are the advantages of running DW Spectrum as a container? Thank you

**Comment by thehomerepot** [comment]
Basically the same advantages as running any docker container.

The software is self-contained
The actual configuration and recordings are stored outside the container
I can migrate the server from 1 machine to another and maintain all configuration
I can quickly, easily, and safely test updated versions of the software and roll back to a different version if needed.

In order to make this most effective I run a small VM with DW Spectrum that has a persistent UUID and hardware configuration that holds my camera licenses. This machine does nothing but host my licenses. This allows me to spin up as many instances of DW Spectrum via Docker across multiple machines (or even on the same machine) and not worry about the migration or persistence of the licensing.

**Comment by paxsecurity** [comment]
That is very interesting. 
And please pardon my ignorance, I am not familiar with docker. (Frantically reading the docs now)

So the VM with persistent UUID + hardware you have running, is it also the main DW server? or does each container you create have identical hardwareid and you can move licenses from one machine to another?

**Comment by thehomerepot** [comment]
No, licenses should not exist on any instance of DW Spectrum running from within docker. Every docker container I create with DW spectrum will have a different HWID. This is the point of having a minimal VM running in which I can control the UUID and hardware included in it. If done properly, I can migrate this VM between any machine and persist my licenses without issue. With v3.1 of DW Spectrum, the VM is less important because you can deactivate and reactivate licenses without contacting support, but you should still not tie them to instances in a docker container because you can only deactivate licenses from the machine with the HWID those licenses were tied to. So if you blow away a docker container and lose your HWID, you would have to contact support.

The VM I tie my licenses to does nothing but sit inside my DW Spectrum server cluster and provide licenses to my other instances.

**Comment by paxsecurity** [comment]
Okay now I understand the purpose of the VM. That is very clever. 
The server cluster you have set up, how are the hosts networked, and how are the cameras networked at the edge?
Do you mind if we can link up over email? stas@paxsecurity.net

**Pull request merged**
